<?php

namespace FluffyRollBundle\Repository;

/**
 * TeddyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeddyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAllOrderedByName()
    {
        return $this->findBy([], ['name' => 'ASC']);
    }

    /**
     * @return array
     */
    public function findAllRandomly()
    {
        return $this->createQueryBuilder('t')
            ->orderBy('RAND()')
            ->getQuery()
            ->getResult();
    }
}
